/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import 'react-native-gesture-handler';

AppRegistry.registerComponent(appName, () => App);

const taskNames = [
  "everybody drink",
  "choose two people to drink with",
  "choose who to drink",
  "Those with a tattoo, drink!",
  "Last person that went to the loo, drink!",
  "drink!",
  "If you've kissed the same gender, drink!",
  "If you have cried in the past month, drink!",
  "Drink for every one sibling you have",
  "Last person to touch the floor drinks!",
  "The one who visited the most countries, drink!",
  "The one who visited the least amount of countries, drink!",
  "Who can speak the most languages? Drink!",
  "Wearing glasses? Drink!",
  "Last person to raise their hand and say \"meow\", drinks!",
  "Ate rice today? Drink!",
  "Chug your drink. Bottom's up!",
  "Everybody bottom's up!",
  "Choose someone to bottom's up!",
  "Last person to balance on one leg, drinks!",
  "For one round, everyone converse without making eye contact",
  "Drink if you've been to a music concert",
  "Toss a coin. If you guessed correctly, everybody else drinks.",
  "Drink if you never gone surfing.",
  "Drink if you never broken a bone.",
  "Drink if you have ruined someone elses vacation.",
  "Drink if you tried to cut my own hair.",
  "Drink if you have dyed your hair a crazy color.",
  "Drink if you have had a physical fight with your best friend.",
  "Have you peed in pool before?",
  "Whats the most embarrassing thing youve ever done while drunk?",
  "What's your guilty pleasure?",
  "How many have you slept with?",
  "The most recent lie you told",
  "Weirdest place that you did it?",
  "Celebrity you masturbated to",
  "How many people have you sent nudes to?",
  "What's your biggest fear?",
  "Name three countries in five seconds",
  "Two countries beginning with the letter D",
  "What is your wildest fetish?",
  "What's something you're glad your parents don't know?",
  "Have you ever cheated on someone?",
  "What's the worst intimate experience you've had?",
  "Who would you like to kiss in this room? If they feel the same way, kiss!",
  "What's the worst date you've been on?",
  "Have you ever lied to get out of a bad date?",
  "Name three animals beginning with C",
  "Top three turn ons",
  "Tell us about your first kiss!",
  "Who here has the nicest bum?",
  "Who is a person you most regret kissing?",
  "What's the naughtiest thing you've done in public?",
  "What do most people think is true about you, but isnt?",
  "What do most people think is true about you, but isnt?",
  "Name a country that starts with an A, but doesn't end with A",
  "What is something your friends would never expect that you do?",
  "Name 3 zombie films!",
  "What is the silliest thing you have an emotional attachment to?",
  "What is the most embarrassing thing your parents have caught you doing?",
  "When was the most inappropriate time you farted?",
  "What is the most embarrassing thing in your room?",
  "Tell us about the last time someone unexpectedly walked in on you while you were naked.",
  "Tell us something you dont want the person on the left to know.",
  "famous director or a famous actor?",
  "live in a cave or live in a tree house?",
  "be able to teleport anywhere or be able to read minds?",
  "be beautiful/handsome but stupid or intelligent but ugly?",
  "never be able to wear pants or never be able to wear shorts?",
  "super sensitive taste or super sensitive hearing?",
  "have out of control body hair or a strong, pungent body odor?",
  "accidentally be responsible for the death of a child or accidentally be responsible for the deaths of three adults?",
  "Last person to touch the wall drinks",
  "Rice cooker/pressure cooker",
  "White underwear/knickers",
  "Take/eat lime with your drink or else drink double",
  "Eat one teaspoon of salt",
  "Take one piece of clothing off or drink",
  "Tell a joke... or drink",
  "Touch your nose with your tongue!",
  "Shuffle and drink!",
  "Do the Gangnam style dance while drinking",
  "For one round, everyone sing everything you talk",
  "For one round, everyone talk at a high pitch!",
  "Add on \"fuck that\" to the end of everything you say, for one round",
  "Send a voice note to a chosen person by the team singing Let It Go",
  "Speak in a british accent... but in your native language!",
  "Recite the alphabet backwards starting from J",
  "Take a sip from everyone's drink",
  "Do a dance move from a music video... If the team can't guess, then drink",
  "Do 5 squats with one leg!",
  "Compliment the person on your right",
  "Keep 3 ice cubes in your mouth until they melt",
  "Say something dirty to the person on your left",
  "Yell out the first word that comes to your mind",
  "Keep your eyes closed until it's your turn again",
  "Do your best moon walk while drinking!",
  "Twerk for 10 seconds",
  "Howl like a wolf for as long as you can",
  "Drink without using your hands",
  "Pole dance with an imaginary pole",
  "Love shot with the person across you",
  "Lick your elbow! If you can't, then drink!",
  "Draw the person on your right",
  "Do the Macarena dance",
  "Attempt to do a magic trick.",
  "Be someones pet for the next 5 minutes.",
  "Attempt to break dance for 30 seconds.",
  "Let the group give you a new hairstyle.",
  "Do the worm.",
  "Sniff the armpits of everyone in the room.",
  "Belly dance like your life depended on it.",
  "Play a song on by slapping your butt cheeks till someone guesses the song.",
  "Drink a small cup or shot of a concoction that the group makes. (Dont make anything that might cause bodily harm. No visits to the emergency room.).",
  "Make every person in the group smile, keep going until everyone has cracked a smiled.",
  "Try to juggle 2 or 3 items of the groups choosing.",
  "Walk on your hands from one side of the room to the other. You can ask someone to hold your legs if necessary.",
  "Get slapped on the face by the person of your choosing.",
  "Seduce a member of the same gender in the group.",
  "Crawl race with the person on your right"
];

module.exports = taskNames;
